/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nlt_testjni_MainActivity */

#ifndef _Included_com_nlt_testjni_MainActivity
#define _Included_com_nlt_testjni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nlt_testjni_MainActivity
 * Method:    getSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_nlt_testjni_MainActivity_getSum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_nlt_testjni_MainActivity
 * Method:    subString
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nlt_testjni_MainActivity_subString
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_nlt_testjni_MainActivity
 * Method:    setStudentAge
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_nlt_testjni_MainActivity_setStudentAge
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
