/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nlt_testjni_MainActivity */
#include <android/log.h>
#ifndef LOG_TAG
#define LOG_TAG "Seven"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#endif

#ifndef _Included_com_nlt_testjni_MainActivity
#define _Included_com_nlt_testjni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nlt_testjni_MainActivity
 * Method:    getSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_nlt_testjni_MainActivity_getSum
        (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
