/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nlt_testjni_MainActivity_Student */

#ifndef _Included_com_nlt_testjni_MainActivity_Student
#define _Included_com_nlt_testjni_MainActivity_Student
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
